### ISSUE TITLE
[Bug]: mac版的不能用吗？

### ISSUE THREAD

**Issue by VKWF** [taozhiyu/TyProAction#1877]
### 过程描述

我下载（更新）了xxx，安装xxxxx

### 情况描述

-

### 版本号

1.2.4

### 是否为稳定版

稳定版

**Comment by taozhiyu** [comment]
您好，理论上解密算法是差不多的，

但是没有设备实验并且没有证书打包，

因此目前本仓库应该不会有mac版。

如果您有Python相关基础可以尝试clone本库进行修改运行，

其中主要解密函数位于`scripts/libs/decoding.py` 其中的 extractWdec 为解密函数，

解密后需要手动修改并重新打包。
