### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 610069895** [taozhiyu/TyProAction#2669]
### 过程描述

我下载（更新）了1.2.5，安装1.2.5，但是拷贝到安装目录下管理员运行Typro-Update-V1.2.5.exe无法激活，同时我也尝试了替换asar-file-V1.2.5.zip，后离线激活，但是注册机我提交了两个小时并没有返回您的离线激活码为/Your offline activation code is:token
![image](https://user-images.githubusercontent.com/51732190/167301232-792f6496-0709-49ba-bc02-ce09f59714ef.png)

### 情况描述

我下载（更新）了1.2.5，安装1.2.5，但是拷贝到安装目录下管理员运行Typro-Update-V1.2.5.exe无法激活，同时我也尝试了替换asar-file-V1.2.5.zip，后离线激活，但是注册机我提交了两个小时并没有返回您的离线激活码为/Your offline activation code is:token

### 版本号

1.2.5

### 是否为稳定版

稳定版

**Comment by taozhiyu** [comment]
应该是机器人响应故障了。。。

应该是github action的问题

我帮你重新生成了。

release里的exe和asar文件是同样的文件，是相同的补丁，

asar文件为了方便快速打补丁，然后exe是为了方便自动更新
