### ISSUE TITLE
⚠️ ⚠️ 请不要涉及其他任何软件 ⚠️ ⚠️ 

### ISSUE THREAD

**Issue by taozhiyu** [taozhiyu/TyProAction#281]
本仓库仅用来学习研究 github action 之用，

下载体验后请在24小时内从设备上彻底删除，

请勿用于任何违法违规、商业盈利、侵权等行为！

一切违规用途与本仓库及本人无关

**Comment by chovieq** [comment]
eyJ2Ijoid2lufDEuMi41IiwiaSI6IkcxMWNsb2JwQ0EiLCJsIjoiTEFQVE9QLUhQRVNVUTdVIHwgQVNVUyB8IFdpbmRvd3MifQ==

**Comment by huangzheng2016** [comment]
eyJ2Ijoid2lufDEuMi41IiwiaSI6InpHQlA4MUhKVFEiLCJsIjoiSFoyMDE2LVBDIHwgaHoyMDE2IHwgV2luZG93cyJ9
