### ISSUE TITLE
⚠️⚠️Please DO NOT talk about any irrelevant software⚠️⚠️

### ISSUE THREAD

**Issue by taozhiyu** [taozhiyu/TyProAction#285]
This repository is for learning and researching `github actions` **ONLY**

Please delete it **COMPLETELY** from your device within 24 hours after downloading it.

Please DO NOT use it for any illegal, commercial or infringing purposes!

All illegal uses are NOT the responsibility of the repository or myself.

**Comment by braveshae** [comment]
11

**Comment by db520xx** [comment]
eyJ2Ijoid2lufDEuMi41IiwiaSI6IjdHNHl3RnhCRkYiLCJsIjoiTEFQVE9QLUFTUFBHNVBOIHwgU2FucGllY2UgfCBXaW5kb3dzIn0=

**Comment by lkliwanglin** [comment]
eyJ2Ijoid2lufDEuMi41IiwiaSI6ImFGSEpJbk5ja3EiLCJsIjoiT0tMSyB8IE1TSS1OQiB8IFdpbmRvd3MifQ==

**Comment by chenchunlai** [comment]
eyJ2Ijoid2lufDEuMy4yLWRldiIsImkiOiIyc1JMMWZvRm1PIiwibCI6Ik1BR0lDQk9PSy1QUk8gfCBBaSB8IFdpbmRvd3MifQ==

**Comment by ReyXRey** [comment]
+gXyikXfphBEeTVrC8ZAgEki5yAmJZrSlA1VbwqBWI6J6lhwCqRz2/1xbvpAXV7YveCn6Xwfjfu5G/AptFwy3yd1Zw9wGWiKODgK67jOFChCdlRmmYk47wBDDru0QOeMNXMbgqem7MbvvQElAYIHFoLWE8nlCt+Whe2K/ocWDIIhQg6Cj8Azhrj3OoqZoyHjM2lxL6diYFg4dcKAa4can0yjYYeYgGa7Q4ihnM+Nn4YJ6y+aRg57q4SGHRa/UJ9HQnwWi2JWFRuJEQvGrR3QM7MWnY9AWaUmbnDE7QfT0i/mopNCUknPqWtRpya3vLkDBWqmwy9HTniBmxlWcV101mA==

**Comment by Johnny-zbb** [comment]
eyJ2Ijoid2lufDEuMy4yLWRldiIsImkiOiJIYW1zZlNRR2lnIiwibCI6IkRFU0tUT1AtR0FWUUQ1UiB8IEpvaG5ueSB8IFdpbmRvd3MifQ==

**Comment by Ctu-SiTuShenPeng** [comment]
eyJ2IjoibGludXh8MS4xLjUiLCJpIjoiYXh3MGlsdFFhMSIsImwiOiJjdHUgfCBjdHUgfCBMaW51eCJ9

**Comment by tututu-tutu** [comment]
eyJ2Ijoid2lufDEuMy4yLWRldiIsImkiOiJhVVZIb3MxQ2FhIiwibCI6IllaTC1IVUFXRUktTUFURSB8IDEgfCBXaW5kb3dzIn0=

**Comment by HSdiana** [comment]
eyJ2Ijoid2lufDEuMi41IiwiaSI6ImthbDFkc3FkNlUiLCJsIjoiTEFQVE9QLUswSTdST1IyIHwgemhpeGluamlhIHwgV2luZG93cyJ9
