### ISSUE TITLE
[Bug]:请问，这个如何在本地执行？ 

### ISSUE THREAD

**Issue by akensir** [taozhiyu/TyProAction#3230]
### 过程描述

我下载了 TyProAction-1.2.5 ，但是 keygen.js无法在本地运行，我已经安装了，python-3.10.4-amd64 和 python-3.10.4-amd64。

### 情况描述

希望能在本地执行，生成离线注册码。

### 版本号

1.2.5

### 是否为稳定版

稳定版

### 其他内容

ken@kensir.com
vx:ken_jia

**Comment by taozhiyu** [comment]
你好，目前不支持本地运行，请直接使用模板提交issue
