### ISSUE TITLE
[Bug]: 未检测到Typora...

### ISSUE THREAD

**Issue by lon91ong** [taozhiyu/TyProAction#3783]
### 过程描述

我下载（更新）了Typro-Update-V1.2.5.exe，直接运行显示"未检测到Typora, 请先安装正版..."
先后测试安装了官方1.2.5和1.2.4, 都是一样的结果

### 情况描述

未检测到Typora, 请先安装正版...

### 版本号

V1.2.5

### 是否为稳定版

稳定版

### 其他内容

稳定版1.2.5和测试版1.3.2都测试过, 一样的问题

**Comment by taozhiyu** [comment]
az收到等待排查，先临时手动复制覆盖asar使用吧

**Comment by taozhiyu** [comment]
你好，请问你的系统是64位的windows吗？
暂未适配arm和x32版本，我这里目前没有发现这个问题。
如果确认是64位windows请贴一下相关系统版本截图方便排查

**Comment by lon91ong** [comment]
是win10 x64, 如下图所示
![2022-05-16_080236](https://user-images.githubusercontent.com/16462258/168500219-afe23915-a511-4a8c-8fcd-913d79f1dd77.png)

**Comment by taozhiyu** [comment]
检查的注册表
SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{37771A20-7167-44C0-B322-FD3E54C56156}_is1
因为inno读取32位和64位的注册表不一样，暂时没有适配，但你是64位那我就不知道了，你手动补一下注册表看看呢？
也有可能是没读取到。。。

**Comment by taozhiyu** [comment]
自动更新其实不麻烦，主要就是各种架构的适配。。。他最多的时候一共有8个版本。。。

**Comment by lon91ong** [comment]
注册表 HKEY_CURRENT_USER下有正常的安装信息
而HKEY_LOCAL_MACHINE下没有
![2022-05-17_101657](https://user-images.githubusercontent.com/16462258/168714851-f24cb629-211a-40ae-89a7-178949df6506.png)

**Comment by taozhiyu** [comment]
收到，看一下能不能兼容，不知道HKEY_CURRENT_USER需不需要特殊权限
