### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lcyan** [taozhiyu/TyProAction#5242]
### 过程描述

我下载（更新）了1.3.2-dev，安装1.3.2-dev

### 情况描述

双击打开md文件，第一次打开不显示内容，不关闭第一次打开的，继续双击打开md后缀的文件，正常显示内容

### 版本号

1.3.2-dev

### 是否为稳定版

开发版

**Comment by taozhiyu** [comment]
这会不会是官方的bug？
我也遇到了

**Comment by taozhiyu** [comment]
不知道官方版的dev有没有这个问题，先加个待补充吧

**Comment by taozhiyu** [comment]
已确认是项目的问题，待修复。
感谢

**Comment by taozhiyu** [comment]
已经修复，
请更新到1.3.3-dev

https://github.com/taozhiyu/TyProAction/releases/tag/v1.3.3-dev
