### ISSUE TITLE
[Bug]: invalid activation token

### ISSUE THREAD

**Issue by nlzq** [taozhiyu/TyProAction#5606]
### 过程描述

typora 官网下载安装

![image](https://camo.githubusercontent.com/6a7af665478f723da9e3f9135666feb7bfb87a24333e3fd298bf04041a984686/68747470733a2f2f7069632e726d622e62647374617469632e636f6d2f626a682f35353237363463626437373164303837363565363936323334613934366663372e676966)

### 情况描述

![image](https://user-images.githubusercontent.com/95120835/170813990-a465225e-8905-423c-804c-1ce5cd7d26a9.png)

### 版本号

1.2.5

### 是否为稳定版

稳定版

**Comment by nlzq** [comment]
![image](https://user-images.githubusercontent.com/95120835/170814383-f5bdf6c6-c49e-4055-afc5-44ff0ebb192c.png)

**Comment by taozhiyu** [comment]
Linux吗？暂时只支持64位windows呢

**Comment by nlzq** [comment]
Windows10 是 64 位的



---Original---
From: ***@***.***&gt;
Date: Sat, May 28, 2022 18:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [taozhiyu/TyProAction] [Bug]: invalid activation token (Issue#5606)




 
Linux吗？暂时只支持64位windows呢

**Comment by nlzq** [comment]
@taozhiyu 
1. 下载这个
![image](https://user-images.githubusercontent.com/95120835/170831119-1a4333bf-93e3-4dc7-8d98-fe67942b684d.png)

2. 替换 typora resources 目录下的 app.asar
![image](https://user-images.githubusercontent.com/95120835/170831156-300e062a-e24c-4ef3-bbf4-6e8e061f5cec.png)

3. 新建 issue
![image](https://user-images.githubusercontent.com/95120835/170831172-abc0092f-701f-469d-8ca8-bc1df94e5309.png)
![image](https://user-images.githubusercontent.com/95120835/170831177-28948ccd-2b56-49df-9127-42e975e9c394.png)

4. 直接提交
![image](https://user-images.githubusercontent.com/95120835/170831185-41148e60-59b8-4146-b991-a045a3113391.png)

5. 然后离线激活，就提示这个
![image](https://user-images.githubusercontent.com/95120835/170831199-c1605545-669c-4441-8332-89bd03189150.png)


是我操作有遗漏的地方么？还是错了

**Comment by nlzq** [comment]
@taozhiyu 
typora 是官网下载
![image](https://user-images.githubusercontent.com/95120835/170831287-2f09b3af-8973-45ec-986e-e0ab31bfe1ad.png)

**Comment by taozhiyu** [comment]
唔你是不是没有输入机器码直接点的确定。。。

要把machine code粘贴到那个注释里的
（我录的gif是因为那个就是我的机器码了。。。）

**Comment by hammerflyhub** [comment]
遇到同样的情况。今天有更新，点了自动更新后用不了了。然后再下载就提示invalid activation token

**Comment by nlzq** [comment]
机器码跟你那个一样的
都试过了，机器码、用户名、激活码 都自定义输入过



 
From: 涛之雨
Date: 2022-05-29 03:46
To: taozhiyu/TyProAction
CC: nlzq; Author
Subject: Re: [taozhiyu/TyProAction] [Bug]: invalid activation token (Issue #5606)
唔你是不是没有输入机器码直接点的确定。。。
要把machine code粘贴到那个注释里的
（我录的gif是因为那个就是我的机器码了。。。）

**Comment by nlzq** [comment]
@taozhiyu 原来是要写注释里面，我给写外面了，我的！！！

**Comment by taozhiyu** [comment]
> @taozhiyu 原来是要写注释里面，我给写外面了，我的！！！

唔，其实应该也是可以的，我记得我适配了啊（问题不大）
