### ISSUE TITLE
[Bug]: 主题文件夹地址打开错误

### ISSUE THREAD

**Issue by meazin** [taozhiyu/TyProAction#6498]
### 过程描述

我安装并更新的版本是 typora 1.3.3-dev。
在 偏好设置-外观-打开主题文件夹 时，弹出错误，原因为后缀地址斜杠符号错误，导致地址文件夹查找不到。

![image](https://user-images.githubusercontent.com/21169751/171357966-15b03225-b21a-4594-920b-3342128eaaf0.png)

### 情况描述

预期情况：地址拼接正确

### 版本号

V 1.3.3-dev

### 是否为稳定版

开发版

**Comment by taozhiyu** [comment]
唔，我应该没有修改这里啊，我有抽空看一下吧

**Comment by taozhiyu** [comment]
官方版1.3.3-dev的bug，应该是没有区分linux版和win版造成的。。。

![image](https://user-images.githubusercontent.com/49258735/171451838-9b42959f-ca0f-43e2-8eeb-08f930eb28af.png)

等官方修复吧
